<?php

class InflectV {
	static $irregular = [
		['misunderstand', 'misunderstood', 'misunderstood|misunderstanden'],
		['quick-freeze', 'quick-froze', 'quick-frozen'],
		['underclothe', 'underclad|underclothed', 'underclad|underclothed'],
		['green-light', 'green-lit|green-lighted', 'green-lit|green-lighted'],
		['interbreed', 'interbred', 'interbred'],
		['underbuild', 'underbuilt', 'underbuilt'],
		['overclothe', 'overclad|overclothed', 'overclad|overclothed'],
		['test-drive', 'test-drove|test-drave', 'test-driven'],
		['force-feed', 'force-fed', 'force-fed'],
		['sight-read', 'sight-read', 'sight-read|sight-readen'],
		['undershoot', 'undershot', 'undershot|undershotten'],
		['overshrink', 'overshrank|overshrunk', 'overshrunk|overshrunken'],
		['undersleep', 'underslept', 'underslept'],
		['handspring', 'handsprang|handsprung', 'handsprung|handsprang'],
		['understand', 'understood', 'understood|understanden'],
		['overstride', 'overstrode|overstrided', 'overstridden|overstrode|overstrid|overstridded'],
		['overstrike', 'overstruck', 'overstruck|overstricken'],
		['overstring', 'overstrung|overstringed', 'overstrung|overstringed'],
		['overstrive', 'overstrove', 'overstriven'],
		['underthrow', 'underthrew|underthrowed', 'underthrown|underthrowed'],
		['interweave', 'interwove', 'interwoven'],
		['ghostwrite', 'ghostwrote|ghostwrit', 'ghostwritten|ghostwrit'],
		['underwrite', 'underwrote|underwrit', 'underwritten|underwrit'],
		['underbear', 'underbore|underbare', 'underborne|underborn'],
		['misbecome', 'misbecame', 'misbecome'],
		['underbind', 'underbound', 'underbound'],
		['frostbite', 'frostbit', 'frostbitten'],
		['overbreed', 'overbred', 'overbred'],
		['overbuild', 'overbuilt', 'overbuilt'],
		['broadcast', 'broadcast', 'broadcast'],
		['simulcast', 'simulcast', 'simulcast'],
		['undercast', 'undercast', 'undercast'],
		['mischoose', 'mischose', 'mischosen'],
		['underdraw', 'underdrew', 'underdrawn'],
		['overdrink', 'overdrank|overdrunk|overdrinked', 'overdrunk|overdrank|overdrinked|overdrunken'],
		['overdrive', 'overdrove|overdrave', 'overdriven'],
		['misbefall', 'misbefell|misbefelled', 'misbefallen|misbefelled'],
		['hand-feed', 'hand-fed', 'hand-fed'],
		['self-feed', 'self-fed', 'self-fed'],
		['spoonfeed', 'spoonfed', 'spoonfed'],
		['underfeed', 'underfed', 'underfed'],
		['undergird', 'undergirded|undergirt', 'undergirded|undergirt'],
		['undergrow', 'undergrew|undergrowed', 'undergrown|undergrowed'],
		['underhang', 'underhung|underhanged', 'underhung|underhanged'],
		['underkeep', 'underkept', 'underkept'],
		['forthlead', 'forthled', 'forthled'],
		['underlead', 'underled', 'underled'],
		['forthleap', 'forthleaped|forthleapt|forthlept|forthlope', 'forthleaped|forthleapt|forthlopen'],
		['overlearn', 'overlearned|overlearnt', 'overlearned|overlearnt'],
		['overleave', 'overleft', 'overleft|overlaft'],
		['backlight', 'backlit|backlighted', 'backlit|backlighted'],
		['proofread', 'proofread', 'proofread|proofreaden'],
		['undersell', 'undersold', 'undersold'],
		['overshake', 'overshook', 'overshaken'],
		['overshine', 'beshone|beshined', 'beshone|beshined'],
		['overshoot', 'overshot', 'overshot|overshotten'],
		['oversleep', 'overslept', 'overslept'],
		['backslide', 'backslid', 'backslid|backslidden'],
		['overslide', 'overslid', 'overslid|overslidden'],
		['forespeak', 'forespoke|forespake', 'forespoken|forespoke'],
		['overspend', 'overspent', 'overspent'],
		['overspill', 'overspilled|overspilt', 'overspilled|overspilt'],
		['overstand', 'overstood', 'overstood|overstanden'],
		['withstand', 'withstood', 'withstood|withstanden'],
		['overstrew', 'overstrewed', 'overstrewn|overstrewed'],
		['outstride', 'outstrode|outstrided', 'outstridden|outstrode|outstrid|outstridded'],
		['hamstring', 'hamstrung|hamstringed', 'hamstrung|hamstringed'],
		['outstrive', 'outstrove', 'outstriven'],
		['overswing', 'overswang|overswung', 'overswung|overswungen'],
		['undertake', 'undertook|undertaked', 'undertaken'],
		['overthrow', 'overthrew|overthrowed', 'overthrown|overthrowed'],
		['outthrust', 'outthrust|outthrusted', 'outthrust|outthrusted'],
		['handwrite', 'handwrote|handwrit', 'handwritten|handwrit'],
		['overwrite', 'overwrote|overwrit', 'overwritten|overwrit'],
		['overbear', 'overbore|overbare', 'overborne|overborn'],
		['browbeat', 'browbeat', 'browbeaten|browbeat'],
		['overbeat', 'overbeat', 'overbeaten|overbeat'],
		['misbeget', 'misbegot|misbegat', 'misbegotten|misbegot'], //
		['overbend', 'overbent|overbended', 'overbent|overbended'],
		['underbet', 'underbet|underbetted', 'underbet|underbetted'], //
		['underbid', 'underbid', 'underbid'], //
		['overblow', 'overblew', 'overblown'],
		['outbreak', 'outbroke', 'outbroken'],
		['underbuy', 'underbought', 'underbought'],
		['downcast', 'downcast', 'downcast'],
		['forecast', 'forecast', 'forecast'],
		['overcast', 'overcast', 'overcast'],
		['telecast', 'telecast', 'telecast'],
		['typecast', 'typecast', 'typecast'],
		['unclothe', 'unclad|unclothed', 'unclad|unclothed'],
		['overcome', 'overcame', 'overcome|overcomen'],
		['clearcut', 'clearcut', 'clearcut'], //
		['crosscut', 'crosscut', 'crosscut'], //
		['intercut', 'intercut', 'intercut'], //
		['undercut', 'undercut', 'undercut'], //
		['underdig', 'underdug', 'underdug'], //
		['overdraw', 'overdrew', 'overdrawn'],
		['withdraw', 'withdrew', 'withdrawn'],
		['outdrink', 'outdrank|outdrunk|outdrinked', 'outdrunk|outdrank|outdrinked|outdrunken'],
		['undereat', 'underate', 'undereaten'],
		['overfeed', 'overfed', 'overfed'],
		['test-fly', 'test-flew', 'test-flown'],
		['refreeze', 'refroze', 'refrozen'],
		['unfreeze', 'unfroze', 'unfrozen'],
		['underget', 'undergot|undergat', 'undergot|undergotten'], //
		['overgive', 'overgave', 'overgiven'],
		['overgrow', 'overgrew|overgrowed', 'overgrown|overgrowed'],
		['overhang', 'overhung|overhanged', 'overhung|overhanged'],
		['overhear', 'overheard', 'overheard'],
		['underhew', 'underhewed|underhew', 'underhewed|underhewn'],
		['underhit', 'underhit', 'underhit'], //
		['withhold', 'withheld', 'withheld|withholden'],
		['foreknow', 'foreknew', 'foreknown|foreknowen'],
		['overlade', 'overladed', 'overladen|overladed'],
		['interlay', 'interlaid|interlayed', 'interlaid|interlayed'],
		['underlay', 'underlaid|underlayed', 'underlaid|underlayed'],
		['overlead', 'overled', 'overled'],
		['overleap', 'overleaped|overleapt|overlept|overlope', 'overleaped|overleapt|overlopen'],
		['mislearn', 'mislearned|mislearnt', 'mislearned|mislearnt'],
		['forleave', 'forleft', 'forleft|forlaft'],
		['underlet', 'underlet|underleet', 'underlet|underletten'], //
		['underlie', 'underlay', 'underlain'],
		['underpay', 'underpaid|underpayed', 'underpaid|underpayed'],
		['underput', 'underput', 'underput|underputten'], //
		['foreread', 'foreread', 'foreread|forereaden'],
		['override', 'overrode|overrid', 'overridden|overrid'],
		['underrun', 'underran', 'underrun'],
		['soothsay', 'soothsaid', 'soothsaid'],
		['sightsee', 'sightsaw', 'sightseen'],
		['undersee', 'undersaw', 'underseen'],
		['oversell', 'oversold', 'oversold'],
		['forshape', 'forshaped|forshope', 'forshaped|forshapen'],
		['misshape', 'misshaped|misshope', 'misshaped|misshapen'],
		['outshine', 'beshone|beshined', 'beshone|beshined'],
		['misshoot', 'misshot', 'misshot|misshotten'],
		['foreshow', 'foreshowed|foreshew', 'foreshown|foreshowed|foreshewed'],
		['housesit', 'housesat|housesate', 'housesat|housesitten'], //
		['overslip', 'overslipped|overslipt', 'overslipped|overslipt'],
		['forspeak', 'forspoke|forspake', 'forspoken|forspoke'],
		['misspeak', 'misspoke|misspake', 'misspoken|misspoke'],
		['misspell', 'misspelled|misspelt', 'misspelled|misspelt'],
		['forspend', 'forspent', 'forspent'],
		['misspend', 'misspent', 'misspent'],
		['outspend', 'outspent', 'outspent'],
		['bespread', 'bespread|bespreaded', 'bespread|bespreaded'],
		['forstand', 'forstood', 'forstood|forstanden'],
		['bestride', 'bestrode|bestrided', 'bestridden|bestrode|bestrid|bestridded'],
		['forswear', 'forswore', 'forsworn'],
		['outswear', 'outswore', 'outsworn'],
		['overtake', 'overtook|overtaked', 'overtaken'],
		['foretell', 'foretold|foretelled', 'foretold|foretelled'],
		['outthink', 'outthought|outthinked', 'outthought|outthinked'],
		['misthrow', 'misthrew|misthrowed', 'misthrown|misthrowed'],
		['outthrow', 'outthrew|outthrowed', 'outthrown|outthrowed'],
		['overwear', 'overweared|overwore', 'overweared|overworn'],
		['overwork', 'overworked|overwrought', 'overworked|overwrought'],
		['miswrite', 'miswrote|miswrit', 'miswritten|miswrit'],
		['forbear', 'forbore|forbare', 'forborne|forborn'],
		['misbear', 'misbore|misbare', 'misborne|misborn'],
		['beseech', 'beseeched|besought', 'beseeched|besought'],
		['overbid', 'overbid', 'overbid'], //
		['rebreak', 'rebroke', 'rebroken'],
		['inbreed', 'inbred', 'inbred'],
		['rebuild', 'rebuilt', 'rebuilt'],
		['sunburn', 'sunburned|sunburnt', 'sunburned|sunburnt'],
		['overbuy', 'overbought', 'overbought'],
		['miscast', 'miscast', 'miscast'],
		['podcast', 'podcast', 'podcast'],
		['precast', 'precast', 'precast'],
		['webcast', 'webcast', 'webcast'],
		['misdeal', 'misdealt', 'misdealt'],
		['underdo', 'underdid', 'underdone'],
		['outdraw', 'outdrew', 'outdrawn'],
		['overeat', 'overate', 'overeaten'],
		['misfall', 'misfell|misfelled', 'misfallen|misfelled'],
		['misfeed', 'misfed', 'misfed'],
		['overfly', 'overflew', 'overflown'],
		['forsake', 'forsook', 'forsaken'],
		['overget', 'overgot|overgat', 'overgot|overgotten'], //
		['forgive', 'forgave', 'forgiven'],
		['misgive', 'misgave', 'misgiven'],
		['undergo', 'underwent', 'undergone'],
		['outgrow', 'outgrew|outgrowed', 'outgrown|outgrowed'],
		['mishear', 'misheard', 'misheard'],
		['upheave', 'upheaved|uphove', 'upheaved|uphove|uphoven'],
		['overhit', 'overhit', 'overhit'], //
		['mishold', 'misheld', 'misheld|misholden'],
		['miskeep', 'miskept', 'miskept'],
		['misknow', 'misknew', 'misknown|misknowen'],
		['forelay', 'forelaid|forelayed', 'forelaid|forelayed'],
		['overlay', 'overlaid|overlayed', 'overlaid|overlayed'],
		['mislead', 'misled', 'misled'],
		['offlead', 'offled', 'offled'],
		['outlead', 'outled', 'outled'],
		['outleap', 'outleaped|outleapt|outlept|outlope', 'outleaped|outleapt|outlopen'],
		['relearn', 'relearned|relearnt', 'relearned|relearnt'],
		['unlearn', 'unlearned|unlearnt', 'unlearned|unlearnt'],
		['beleave', 'beleft', 'beleft|belaft'],
		['forlend', 'forlent', 'forlent'],
		['forelie', 'forelay', 'forelain'], //
		['overlie', 'overlay', 'overlain'], //
		['relight', 'relit|relighted', 'relit|relighted'],
		['overpay', 'overpaid|overpayed', 'overpaid|overpayed'],
		['reprove', 'reproved', 'reproved|reproven'],
		['lipread', 'lipread', 'lipread|lipreaden'],
		['misread', 'misread', 'misread|misreaden'],
		['outride', 'outrode|outrid', 'outridden|outrid'],
		['forerun', 'foreran', 'forerun'],
		['overrun', 'overran', 'overrun'],
		['gainsay', 'gainsaid', 'gainsaid'],
		['withsay', 'withsaid', 'withsaid'],
		['foresee', 'foresaw', 'foreseen'],
		['oversee', 'oversaw', 'overseen'],
		['outsell', 'outsold', 'outsold'],
		['missend', 'missent', 'missent'],
		['handset', 'handset', 'handset|handsetten'], //
		['overset', 'overset', 'overset|oversetten'], //
		['withset', 'withset', 'withset|withsetten'], //
		['handsew', 'handsewed', 'handsewn|handsewed|handsewen'],
		['oversew', 'oversewed', 'oversewn|oversewed|oversewen'],
		['beshine', 'beshone|beshined', 'beshone|beshined'],
		['reshoot', 'reshot', 'reshot|reshotten'],
		['babysit', 'babysat|babysate', 'babysat|babysitten'], //
		['withsit', 'withsat|withsate', 'withsat|withsitten'], //
		['bespeak', 'bespoke|bespake', 'bespoken|bespoke'],
		['outspin', 'outspun|outspan', 'outspun'], //
		['upstand', 'upstood', 'upstood|upstanden'],
		['stretch', 'stretched|straught|straight', 'stretched|straught|straight'],
		['bestrew', 'bestrewed', 'bestrewn|bestrewed'],
		['upsweep', 'upswept|upsweeped', 'upswept|upsweeped'],
		['upswell', 'upswelled|upswole|upswelt', 'upswollen|upswelled'],
		['outswim', 'outswam|outswum', 'outswum'], //
		['mistake', 'mistook|mistaked', 'mistaken'],
		['partake', 'partook|partaked', 'partaken'],
		['outtell', 'outtold|outtelled', 'outtold|outtelled'],
		['rethink', 'rethought|rethinked', 'rethought|rethinked'],
		['upthrow', 'upthrew|upthrowed', 'upthrown|upthrowed'],
		['retread', 'retrod|retread|retreaded|retrodden', 'retrodden|retrod|retread|retreaded'],
		['forwear', 'forweared|forwore', 'forweared|forworn'],
		['outwear', 'outweared|outwore', 'outweared|outworn'],
		['unweave', 'unwove', 'unwoven'],
		['overwet', 'overwet|overwetted', 'overwet|overwetted'],
		['cowrite', 'cowrote|writ', 'cowritten'],
		['rewrite', 'rewrote|rewrit', 'rewritten|rewrit'],
		['become', 'became', 'become'],
		['unbend', 'unbent|unbended', 'unbent|unbended'],
		['outbid', 'outbid', 'outbid'],
		['unbind', 'unbound', 'unbound'],
		['recast', 'recast', 'recast'],
		['upcast', 'upcast', 'upcast'],
		['choose', 'chose', 'chosen'],
		['cleave', 'cleft|clove|cleaved|clave', 'cleft|cloven|cleaved'],
		['clothe', 'clad|clothed', 'clad|clothed'],
		['forcut', 'forcut', 'forcut'],
		['redeal', 'redealt', 'redealt'],
		['overdo', 'overdid', 'overdone'],
		['redraw', 'redrew', 'redrawn'],
		['befall', 'befell|befelled', 'befallen|befelled'],
		['refind', 'refound|refand', 'refound|refounden'],
		['misfit', 'misfitted|misfit', 'misfitted|misfit'],
		['outfly', 'outflew', 'outflown'],
		['forbid', 'forbid|forbade|forbad', 'forbidden'],
		['forget', 'forgot|forgat', 'forgotten|forgot'],
		['freeze', 'froze', 'frozen'],
		['forget', 'forgot|forgat', 'forgot|forgotten'],
		['misget', 'misgot|misgat', 'misgot|misgotten'],
		['forego', 'forewent', 'foregone'],
		['overgo', 'overwent', 'overgone'],
		['withgo', 'withwent', 'withgone'],
		['regrow', 'regrew|regrowed', 'regrown|regrowed'],
		['upgrow', 'upgrew|upgrowed', 'upgrown|upgrowed'],
		['uphang', 'uphung|uphanged', 'uphung|uphanged'],
		['unhear', 'unheard', 'unheard'],
		['mishit', 'mishit', 'mishit'],
		['behold', 'beheld', 'beheld|beholden'],
		['inhold', 'inheld', 'inheld|inholden'],
		['uphold', 'upheld', 'upheld|upholden'],
		['misken', 'miskenned|miskent', 'miskenned|miskent'],
		['acknow', 'acknew', 'acknown|acknowen'],
		['forlay', 'forlaid|forlayed', 'forlaid|forlayed'],
		['mislay', 'mislaid|mislayed', 'mislaid|mislayed'],
		['outlay', 'outlaid|outlayed', 'outlaid|outlayed'],
		['re-lay', 're-laid|re-layed', 're-laid|re-layed'],
		['waylay', 'waylaid|waylayed', 'waylaid|waylayed'],
		['belead', 'beled', 'beled'],
		['inlead', 'inled', 'inled'],
		['onlead', 'onled', 'onled'],
		['uplead', 'upled', 'upled'],
		['beleap', 'beleaped|beleapt|belept|belope', 'beleaped|beleapt|belopen'],
		['forlet', 'forlet|forleet', 'forlet|forletten'],
		['sublet', 'sublet|subleet', 'sublet|subletten'],
		['forlie', 'forlay', 'forlain'],
		['alight', 'alit|alighted', 'alit|alighted'],
		['remake', 'remade', 'remade'],
		['unmake', 'unmade', 'unmade'],
		['prepay', 'prepaid|prepayed', 'prepaid|prepayed'],
		['output', 'output', 'output|outputten'],
		['reread', 'reread', 'reread|rereaden'],
		['uprise', 'uprose', 'uprisen'],
		['outrun', 'outran', 'outrun'],
		['forsay', 'forsaid', 'forsaid'],
		['missay', 'missaid', 'missaid'],
		['naysay', 'naysaid', 'naysaid'],
		['missee', 'missaw', 'misseen'],
		['beseek', 'besought', 'besought'],
		['seethe', 'seethed|sod', 'seethed|sodden'],
		['resell', 'resold', 'resold'],
		['upsell', 'upsold', 'upsold'],
		['resend', 'resent', 'resent'],
		['misset', 'misset', 'misset|missetten'],
		['offset', 'offset', 'offset|offsetten'],
		['preset', 'preset', 'preset|presetten'],
		['reshoe', 'reshod|reshoed', 'reshodden|reshod|reshoed'],
		['reshow', 'reshowed|reshew', 'reshown|reshowed|reshewed'],
		['shrink', 'shrank|shrunk', 'shrunk|shrunken'],
		['reshut', 'reshut', 'reshut'],
		['resing', 'resang', 'resung|resungen'],
		['spread', 'spread|spreaded', 'spread|spreaded'],
		['spring', 'sprang|sprung', 'sprung|sprang'],
		['starve', 'starved|starf|storve', 'starved|storven'],
		['stride', 'strode|strided', 'stridden|strode|strid|stridded'],
		['strike', 'struck', 'struck|stricken'],
		['string', 'strung|stringed', 'strung|stringed'],
		['strive', 'strove|strived', 'striven|strived'],
		['betake', 'betook|betaked', 'betaken'],
		['intake', 'intook|intaked', 'intaken'],
		['retake', 'retook|retaked', 'retaken'],
		['uptake', 'uptook|uptaked', 'uptaken'],
		['uptear', 'uptore', 'uptorn'],
		['retell', 'retold|retelled', 'retold|retelled'],
		['thrive', 'throve|thrived|thrave', 'thriven|thrived'],
		['thrust', 'thrust|thrusted', 'thrust|thrusted'],
		['miswed', 'miswed|miswedded', 'miswed|miswedded'],
		['beweep', 'bewept|beweeped', 'bewept|beweeped'],
		['rewind', 'rewound', 'rewound'],
		['unwind', 'unwound', 'unwound'],
		['writhe', 'writhed|wrothe', 'writhed|writhen'],
		['beget', 'begot|begat', 'begotten|begot'],
		['begin', 'began', 'begun'],
		['rebid', 'rebid', 'rebid'],
		['abide', 'abided|abode', 'abided|abidden'],
		['bleed', 'bled', 'bled'],
		['bless', 'blessed|blest', 'blessed|blest'],
		['break', 'broke', 'broken'],
		['breed', 'bred', 'bred'],
		['bring', 'brought', 'brought'],
		['build', 'built', 'built'],
		['burst', 'burst|brast', 'burst|bursten'],
		['catch', 'caught', 'caught'],
		['chide', 'chided|chid|chode', 'chided|chid|chidden'],
		['cling', 'clung', 'clung'],
		['creep', 'crept|creeped|crope', 'crept|creeped|cropen'],
		['recut', 'recut', 'recut'],
		['fordo', 'fordid', 'fordone'],
		['misdo', 'misdid', 'misdone'],
		['outdo', 'outdid', 'outdone'],
		['dream', 'dreamed|dreamt|drempt', 'dreamed|dreamt|drempt'],
		['dress', 'dressed|drest', 'dressed|drest'],
		['drink', 'drank|drunk|drinked', 'drunk|drank|drinked|drunken'],
		['drive', 'drove|drave', 'driven'],
		['dwell', 'dwelt|dwelled', 'dwelt|dwelled'],
		['fight', 'fought', 'fought|foughten'],
		['fling', 'flung', 'flung'],
		['beget', 'begot|begat', 'begot|begotten'],
		['forgo', 'forwent', 'forgone'],
		['grind', 'ground|grinded', 'ground|grinded|grounden'],
		['heave', 'heaved|hove', 'heaved|hove|hoven'],
		['hoist', 'hoisted|hoist', 'hoisted|hoist'],
		['kneel', 'knelt|kneeled', 'knelt|kneeled'],
		['laugh', "laughed|laught|laugh'd|low", "laughed|laught|laugh'd|laughen"],
		['belay', 'belaid|belayed', 'belaid|belayed'],
		['inlay', 'inlaid|inlayed', 'inlaid|inlayed'],
		['onlay', 'onlaid|onlayed', 'onlaid|onlayed'],
		['unlay', 'unlaid|unlayed', 'unlaid|unlayed'],
		['uplay', 'uplaid|uplayed', 'uplaid|uplayed'],
		['learn', 'learned|learnt', 'learned|learnt'],
		['leave', 'left', 'left|laft'],
		['light', 'lit|lighted', 'lit|lighted'],
		['repay', 'repaid|repayed', 'repaid|repayed'],
		['plead', 'pled|pleaded', 'pled|pleaded'],
		['prove', 'proved', 'proved|proven'],
		['input', 'input', 'input|inputten'],
		['reach', 'reached|raught|rought|retcht', 'reached|raught|rought|retcht'],
		['arise', 'arose', 'arisen'],
		['rerun', 'reran', 'rerun'],
		['besee', 'besaw', 'beseen'],
		['beset', 'beset', 'beset|besetten'],
		['inset', 'inset', 'inset|insetten'],
		['reset', 'reset', 'reset|resetten'],
		['upset', 'upset', 'upset|upsetten'],
		['shake', 'shook', 'shaken'],
		['shape', 'shaped|shope', 'shaped|shapen'],
		['shave', 'shaved|shove', 'shaved|shaven'],
		['shear', 'sheared|shore', 'shorn|sheared'],
		['shine', 'shone|shined', 'shone|shined'],
		['shite', 'shited|shit', 'shited|shit'],
		['shoot', 'shot', 'shot|shotten'],
		['resit', 'resat|resate', 'resat|resitten'],
		['sleep', 'slept', 'slept'],
		['slide', 'slid', 'slid|slidden'],
		['sling', 'slung|slang', 'slung'],
		['slink', 'slunk|slinked|slank', 'slunk|slinked|slank'],
		['smell', 'smelled|smelt', 'smelled|smelt'],
		['smite', 'smote|smit', 'smitten|smitted'],
		['sneak', 'sneaked|snuck', 'sneaked|snuck|snucked'],
		['speak', 'spoke|spake', 'spoken|spoke'],
		['speed', 'sped|speeded', 'sped|speeded'],
		['spell', 'spelled|spelt', 'spelled|spelt'],
		['spend', 'spent', 'spent'],
		['spill', 'spilled|spilt', 'spilled|spilt'],
		['split', 'split', 'split'],
		['spoil', 'spoiled|spoilt', 'spoiled|spoilt'],
		['stand', 'stood', 'stood|standen'],
		['stave', 'stove|staved', 'stove|staved|stoven'],
		['steal', 'stole', 'stolen'],
		['stick', 'stuck|sticked', 'stuck|sticked'],
		['sting', 'stung|stang', 'stung'],
		['stink', 'stank|stunk', 'stunk'],
		['strew', 'strewed', 'strewn|strewed'],
		['strip', 'stripped|stript', 'stripped|stript'],
		['swear', 'swore', 'sworn'],
		['sweat', 'sweated|sweat', 'sweated|sweat'],
		['sweep', 'swept|sweeped', 'swept|sweeped'],
		['swell', 'swelled|swole|swelt', 'swollen|swelled'],
		['swing', 'swang|swung', 'swung|swungen'],
		['teach', 'taught|teached', 'taught|teached'],
		['think', 'thought|thinked', 'thought|thinked'],
		['throw', 'threw|throwed', 'thrown|throwed'],
		['tread', 'trod|tread|treaded|trodden', 'trodden|trod|tread|treaded'],
		['awake', 'awoke|awaked', 'awoken|awaked'],
		['weave', 'wove', 'woven'],
		['rewed', 'rewed|rewedded', 'rewed|rewedded'],
		['wreak', 'wreaked|wrought|wrack|wroke', 'wreaked|wrought|wreaken|wroken'],
		['wring', 'wrang|wrung|wringed', 'wrung|wringed'],
		['write', 'wrote|writ', 'written|writ'],
		['bear', 'bore|bare', 'borne|born'],
		['beat', 'beat', 'beaten|beat'],
		['bend', 'bent|bended', 'bent|bended'],
		['bide', 'bided|bode', 'bided|bidden'],
		['bind', 'bound', 'bound'],
		['bite', 'bit', 'bitten'],
		['blow', 'blew', 'blown'],
		['burn', 'burned|burnt', 'burned|burnt'],
		['bust', 'busted|bust', 'busted|bust'],
		['abuy', 'abought', 'abought'],
		['cast', 'cast', 'cast'],
		['clad', 'clad', 'clad'],
		['clap', 'clapped|clapt', 'clapped|clapt'],
		['come', 'came', 'come|comen'],
		['cost', 'cost|costed', 'cost|costed'],
		['crow', 'crowed|crew', 'crowed|crown'],
		['dare', 'dared|durst', 'dared'],
		['deal', 'dealt', 'dealt'],
		['dive', 'dived|dove', 'dived|dove'],
		['undo', 'undid', 'undone'],
		['drag', 'dragged|drug', 'dragged|drug'],
		['draw', 'drew', 'drawn'],
		['fall', 'fell|felled', 'fallen|felled'],
		['feed', 'fed', 'fed'],
		['feel', 'felt', 'felt'],
		['find', 'found|fand', 'found|founden'],
		['flee', 'fled', 'fled'],
		['gild', 'gilded|gilt', 'gilded|gilt'],
		['gird', 'girded|girt', 'girded|girt'],
		['give', 'gave', 'given'],
		['bego', 'bewent', 'begone'],
		['grow', 'grew|growed', 'grown|growed'],
		['hang', 'hung|hanged', 'hung|hanged'],
		['have', 'had', 'had'],
		['hear', 'heard', 'heard'],
		['help', 'helped|holp', 'helped|holpen'],
		['hide', 'hid', 'hidden|hid'],
		['hold', 'held', 'held|holden'],
		['hurt', 'hurt', 'hurt'],
		['keep', 'kept', 'kept'],
		['knit', 'knit|knitted', 'knit|knitted'],
		['know', 'knew', 'known|knowen'],
		['lade', 'laded', 'laden|laded'],
		['lead', 'led', 'led'],
		['lean', 'leaned|leant', 'leaned|leant'],
		['leap', 'leaped|leapt|lept|lope', 'leaped|leapt|lopen'],
		['lend', 'lent', 'lent'],
		['lose', 'lost', 'lost'],
		['make', 'made', 'made'],
		['mean', 'meant', 'meant'],
		['meet', 'met', 'met'],
		['melt', 'melted|molt', 'melted|molten'],
		['need', 'needed', 'needed'],
		['quit', 'quit|quitted', 'quit|quitted'],
		['read', 'read', 'read|readen'],
		['redo', 'redid', 'redone'],
		['rend', 'rent', 'rent'],
		['ride', 'rode|rid', 'ridden|rid'],
		['ring', 'rang|rung', 'rung'],
		['rise', 'rose', 'risen'],
		['rive', 'rived|rove', 'rived|riven'],
		['seek', 'sought', 'sought'],
		['sell', 'sold', 'sold'],
		['send', 'sent', 'sent'],
		['shed', 'shed', 'shed'],
		['shit', 'shit|shitted|shat', 'shit|shitted|shat|shitten'],
		['shoe', 'shod|shoed', 'shodden|shod|shoed'],
		['show', 'showed|shew', 'shown|showed|shewed'],
		['shut', 'shut', 'shut'],
		['sing', 'sang', 'sung|sungen'],
		['sink', 'sank|sunk', 'sunk|sunken'],
		['slay', 'slew|slayed', 'slain|slayed'],
		['slip', 'slipped|slipt', 'slipped|slipt'],
		['slit', 'slit', 'slit|slitten'],
		['spin', 'spun|span', 'spun'],
		['spit', 'spat|spit', 'spat|spit'],
		['stay', 'stayed|staid', 'stayed|staid'],
		['swim', 'swam|swum', 'swum'],
		['take', 'took|taked', 'taken'],
		['tear', 'tore', 'torn'],
		['tell', 'told|telled', 'told|telled'],
		['wake', 'woke|waked', 'woken|waked'],
		['wear', 'weared|wore', 'weared|worn'],
		['weep', 'wept|weeped', 'wept|weeped'],
		['wend', 'wended|went', 'wended|went'],
		['wind', 'wound', 'wound'],
		['work', 'worked|wrought', 'worked|wrought'],
		['zinc', 'zinced|zinked|zincked', 'zinced|zinked|zincked'],
		['bet', 'bet|betted', 'bet|betted'],
		['bid', 'bid', 'bid'],
		['bid', 'bid|bade', 'bid|bidden'],
		['buy', 'bought', 'bought'],
		['cut', 'cut', 'cut'],
		['dig', 'dug|digged', 'dug|digged'],
		['eat', 'ate', 'eaten'],
		['fit', 'fitted|fit', 'fitted|fit'],
		['fly', 'flew', 'flown'],
		['get', 'got|gat', 'got|gotten'],
		['hew', 'hewed|hew', 'hewed|hewn'],
		['hit', 'hit', 'hit'],
		['ken', 'kenned|kent', 'kenned|kent'],
		['lay', 'laid|layed', 'laid|layed'],
		['let', 'let|leet', 'let|letten'],
		['lie', 'lay', 'lain'],
		['mix', 'mixed|mixt', 'mixed|mixt'],
		['mow', 'mowed', 'mowed|mown'],
		['pay', 'paid|payed', 'paid|payed'],
		['pen', 'penned|pent', 'penned|pent'],
		['put', 'put', 'put|putten'],
		['rid', 'rid|ridded', 'rid|ridden|ridded'],
		['run', 'ran', 'run'],
		['saw', 'sawed', 'sawed|sawn'],
		['say', 'said', 'said'],
		['see', 'saw', 'seen'],
		['set', 'set', 'set|setten'],
		['sew', 'sewed', 'sewn|sewed|sewen'],
		['sit', 'sat|sate', 'sat|sitten'],
		['sow', 'sowed|sew', 'sown|sowed'],
		['vex', 'vexed|vext', 'vexed|vext'],
		['wax', 'waxed|wex', 'waxed|waxen'],
		['wed', 'wed|wedded', 'wed|wedded'],
		['wet', 'wet|wetted', 'wet|wetted'],
		['win', 'won', 'won'],
		['do', 'did', 'done'],
		['go', 'went', 'gone'],
		['be', 'was', 'been']
	];

	static $presentparticiple = [
		'arc'=>'arcking',
		'bag'=>'bagging',
		'ban'=>'banning',
		'bar'=>'barring',
		'bat'=>'batting',
		'be'=>'being',
		'bed'=>'bedding',
		'beg'=>'begging',
		'bet'=>'betting',
		'bid'=>'bidding',
		'bin'=>'binning',
		'bit'=>'bitting',
		'blab'=>'blabbing',
		'blet'=>'bletting',
		'blot'=>'blotting',
		'blue'=>'bluing',
		'blur'=>'blurring',
		'bob'=>'bobbing',
		'bog'=>'bogging',
		'brag'=>'bragging',
		'bren'=>'brenning',
		'brim'=>'brimming',
		'brisk'=>'bricking',
		'bud'=>'budding',
		'bum'=>'bumming',
		'but'=>'butting',
		'can'=>'canning',
		'cap'=>'capping',
		'cash'=>'casing',
		'cat'=>'catting',
		'chap'=>'chapping',
		'char'=>'charring',
		'chat'=>'chatting',
		'check'=>'checking',
		'cheer'=>'cheering',
		'chew'=>'chewing',
		'chip'=>'chipping',
		'chop'=>'chopping',
		'chum'=>'chumming',
		'clam'=>'clamming',
		'clap'=>'clapping',
		'clip'=>'clipping',
		'clog'=>'clogging',
		'clot'=>'clotting',
		'club'=>'clubbing',
		'cob'=>'cobbing',
		'cog'=>'cogging',
		'con'=>'conning',
		'co-ordinate'=>'coordinating',
		'cram'=>'cramming',
		'crate'=>'crating',
		'crib'=>'cribbing',
		'crop'=>'cropping',
		'cub'=>'cubbing',
		'cup'=>'cupping',
		'cut'=>'cutting',
		'dab'=>'dabbing',
		'dam'=>'damming',
		'dice'=>'dicing',
		'dig'=>'digging',
		'dim'=>'dimming',
		'din'=>'dinning',
		'dip'=>'dipping',
		'dis'=>'dissing',
		'do'=>'doing',
		'dog'=>'dogging',
		'don'=>'donning',
		'dose'=>'dosing',
		'dot'=>'dotting',
		'drab'=>'drabbing',
		'drag'=>'dragging',
		'draw'=>'drawing',
		'drib'=>'dribbing',
		'drip'=>'dripping',
		'drop'=>'dropping',
		'drub'=>'drubbing',
		'drug'=>'drugging',
		'drum'=>'drumming',
		'dub'=>'dubbing',
		'dun'=>'dunning',
		'fag'=>'fagging',
		'fan'=>'fanning',
		'fat'=>'atting',
		'fib'=>'fibbing',
		'fife'=>'fifing',
		'fin'=>'finning',
		'fire'=>'fring',
		'fit'=>'fitting',
		'flag'=>'flagging',
		'flam'=>'flamming',
		'flap'=>'flapping',
		'flat'=>'flatting',
		'flip'=>'flipping',
		'flip'=>'flipping',
		'flit'=>'flitting',
		'flog'=>'flogging',
		'flop'=>'flopping',
		'fob'=>'fobbing',
		'fog'=>'fogging',
		'frag'=>'fragging',
		'frap'=>'frapping',
		'fret'=>'fretting',
		'frit'=>'fritting',
		'friz'=>'frizzing',
		'ftp'=>'ftping',
		'fur'=>'furring',
		'gad'=>'gadding',
		'gag'=>'gagging',
		'gas'=>'gassing',
		'gem'=>'gemming',
		'get'=>'getting',
		'gib'=>'gibbing',
		'gin'=>'ginning',
		'gin'=>'ginning',
		'glad'=>'gladding',
		'glue'=>'gluing',
		'glut'=>'glutting',
		'gnar'=>'gnarring',
		'bouge'=>'gouging',
		'grab'=>'grabbing',
		'grin'=>'grinning',
		'grit'=>'gritting',
		'groan'=>'groaning',
		'groove'=>'groving',
		'grub'=>'grubbing',
		'guard'=>'gurding',
		'gum'=>'gumming',
		'gut'=>'gutting',
		'hag'=>'hagging',
		'hem'=>'hemming',
		'hip'=>'hipping',
		'hit'=>'hitting',
		'hog'=>'hogging',
		'hop'=>'hopping',
		'hug'=>'hugging',
		'hum'=>'humming',
		'hutch'=>'hutting',
		'invigilate'=>'invigilating',
		'jag'=>'jagging',
		'jam'=>'jamming',
		'jar'=>'jarring',
		'jet'=>'jetting',
		'jib'=>'jibbing',
		'jig'=>'jigging',
		'job'=>'jobbing',
		'jog'=>'jogging',
		'jot'=>'jotting',
		'jug'=>'jugging',
		'jut'=>'jutting',
		'ken'=>'kenning',
		'kid'=>'kidding',
		'knab'=>'knabbing',
		'knap'=>'knapping',
		'knit'=>'knitting',
		'knot'=>'knotting',
		'lag'=>'lagging',
		'lam'=>'lamming',
		'lap'=>'lapping',
		'league'=>'leaguing',
		'let'=>'letting',
		'lip'=>'lipping',
		'lob'=>'lobbing',
		'log'=>'logging',
		'lop'=>'lopping',
		'lot'=>'lotting',
		'lug'=>'lugging',
		'mad'=>'madding',
		'man'=>'manning',
		'map'=>'mapping',
		'mar'=>'marring',
		'mat'=>'matting',
		'merge'=>'merging',
		'mince'=>'minging',
		'mob'=>'mobbing',
		'mog'=>'mogging',
		'mold'=>'molding|moulding',
		'molt'=>'molting|moulting',
		'mop'=>'mopping',
		'nab'=>'nabbing',
		'nag'=>'nagging',
		'nap'=>'napping',
		'net'=>'netting',
		'net'=>'netting',
		'nib'=>'nibbing',
		'nip'=>'nipping',
		'nod'=>'nodding',
		'nut'=>'nutting',
		'pad'=>'padding',
		'pan'=>'panning',
		'pat'=>'patting',
		'peg'=>'pegging',
		'pen'=>'penning',
		'pen'=>'penning',
		'pet'=>'petting',
		'pi'=>'pieing',
		'pig'=>'pigging',
		'pin'=>'pinning',
		'pip'=>'pipping',
		'pique'=>'piquing',
		'pit'=>'pitting',
		'plague'=>'plaguing',
		'plan'=>'planning',
		'plat'=>'platting',
		'plod'=>'plodding',
		'plop'=>'plopping',
		'plot'=>'plotting',
		'plow'=>'plowing|ploughing',
		'plug'=>'plugging',
		'pod'=>'podding',
		'pop'=>'popping',
		'pot'=>'potting',
		'prig'=>'prigging',
		'prim'=>'primming',
		'prod'=>'prodding',
		'prog'=>'progging',
		'prop'=>'propping',
		'pue'=>'puing',
		'pug'=>'pugging',
		'pump'=>'pumping',
		'pun'=>'punning',
		'pup'=>'pupping',
		'pur'=>'purring',
		'put'=>'putting',
		'quail'=>'qualling',
		'quip'=>'quipping',
		'quit'=>'quitting',
		'quiz'=>'quizzing',
		'rag'=>'ragging',
		'ram'=>'ramming',
		'rap'=>'rapping',
		'rap'=>'rapping',
		'rat'=>'ratting',
		'rib'=>'ribbing',
		'rid'=>'ridding',
		'rig'=>'rigging',
		'rim'=>'rimming',
		'rip'=>'ripping',
		'rob'=>'robbing',
		'rot'=>'rotting',
		'rub'=>'rubbing',
		'rue'=>'ruing',
		'run'=>'running',
		'rut'=>'rutting',
		'sag'=>'sagging',
		'sap'=>'sapping',
		'scab'=>'scabbing',
		'scan'=>'scanning',
		'scar'=>'scarring',
		'scorn'=>'scoring',
		'scram'=>'scramming',
		'scram'=>'scramming',
		'scrub'=>'scrubbing',
		'scud'=>'scudding',
		'scum'=>'scumming',
		'set'=>'setting',
		'shab'=>'shabbing',
		'shag'=>'shagging',
		'sham'=>'shamming',
		'sheathe'=>'sheating',
		'shed'=>'shedding',
		'shet'=>'shetting',
		'shin'=>'shinning',
		'ship'=>'shipping',
		'shop'=>'shopping',
		'shot'=>'shotting',
		'shred'=>'shredding',
		'shrug'=>'shrugging',
		'shun'=>'shunning',
		'shut'=>'shutting',
		'sin'=>'sinning',
		'singe'=>'singeing',
		'sip'=>'sipping',
		'sit'=>'sitting',
		'skid'=>'skidding',
		'skim'=>'skimming',
		'skin'=>'skinning',
		'skip'=>'skipping',
		'slag'=>'slagging',
		'slam'=>'slamming',
		'slap'=>'slapping',
		'slat'=>'slatting',
		'sled'=>'sledding',
		'slide'=>'slidding',
		'slip'=>'slipping',
		'slit'=>'slitting',
		'slop'=>'slopping',
		'slub'=>'slubbing',
		'slue'=>'sluing',
		'slug'=>'slugging',
		'slur'=>'slurring',
		'smug'=>'smugging',
		'smut'=>'smutting',
		'snag'=>'snagging',
		'snap'=>'snapping',
		'snip'=>'snipping',
		'snub'=>'snubbing',
		'snug'=>'snugging',
		'sob'=>'sobbing',
		'sod'=>'sodding',
		'sop'=>'sopping',
		'span'=>'spanning',
		'spar'=>'sparring',
		'spat'=>'spatting',
		'spin'=>'spinning',
		'spit'=>'spitting',
		'spit'=>'spitting',
		'split'=>'splitting',
		'spot'=>'spotting',
		'sprag'=>'spragging',
		'sprig'=>'sprigging',
		'spur'=>'spurring',
		'squat'=>'squatting',
		'squib'=>'squibbing',
		'squire'=>'squiring',
		'stab'=>'stabbing',
		'star'=>'starring',
		'stem'=>'stemming',
		'step'=>'stepping',
		'stet'=>'stetting',
		'stir'=>'stirring',
		'stop'=>'stopping',
		'strap'=>'strapping',
		'strip'=>'stripping',
		'stroke'=>'strokeing',
		'strop'=>'stropping',
		'strum'=>'strumming',
		'strut'=>'strutting',
		'stub'=>'stubbing',
		'stud'=>'studding',
		'stum'=>'stumming',
		'stun'=>'stunning',
		'sue'=>'suing',
		'sum'=>'summing',
		'sun'=>'sunning',
		'sup'=>'supping',
		'swab'=>'swabbing',
		'swag'=>'swagging',
		'swap'=>'swapping',
		'swim'=>'swimming',
		'swinge'=>'swingeing',
		'tag'=>'tagging',
		'tan'=>'tanning',
		'tap'=>'tapping',
		'tar'=>'tarring',
		'ted'=>'tedding',
		'thaw'=>'thawing',
		'thin'=>'thinning',
		'thrid'=>'thridding',
		'throb'=>'throbbing',
		'thrum'=>'thrumming',
		'tin'=>'tinning',
		'tinge'=>'tingeing',
		'tip'=>'tipping',
		'tongue'=>'tonguing',
		'tool'=>'tooling',
		'top'=>'topping',
		'tot'=>'totting',
		'toy'=>'toying',
		'trace'=>'tracing',
		'track'=>'tracking',
		'tram'=>'tramming',
		'trap'=>'trapping',
		'trek'=>'trekking',
		'trim'=>'trimming',
		'trip'=>'tripping',
		'trot'=>'trotting',
		'truck'=>'trucking',
		'tub'=>'tubbing',
		'tug'=>'tugging',
		'tun'=>'tunning',
		'twig'=>'twigging',
		'twin'=>'twinning',
		'twit'=>'twitting',
		'vat'=>'vatting',
		'wad'=>'wadding',
		'wag'=>'wagging',
		'war'=>'warring',
		'web'=>'webbing',
		'wed'=>'wedding',
		'wet'=>'wetting',
		'whala'=>'whaling',
		'whap'=>'whapping',
		'whet'=>'whetting',
		'whip'=>'whipping',
		'whir'=>'whirring',
		'whiz'=>'whizzing',
		'wig'=>'wigging',
		'win'=>'winning',
		'wrap'=>'wrapping',
		'zinc'=>'zincking',
	];

	static public function preterite($verb, $only_one=false) {
		foreach (self::$irregular as $i)
			if ($i[0] == $verb) {
				if ($only_one)
					return explode("|", $i[1])[0];
				return $i[1];
			}
		if (array_key_exists($verb, self::$presentparticiple)) {
			$v = self::$presentparticiple[$verb];
			$matches = [];
			preg_match('/([a-zA-Z-]+([a-zA-Z]))\2ing$/', $v, $matches);
			if (count($matches) and $matches[1] == $verb)
				return $verb.$matches[2]."ed";
		}
		if ($verb[strlen($verb)-1] == "e")
			return $verb."d";
		return $verb."ed";
	}

	static public function pastparticiple($verb, $only_one=false) {
		foreach (self::$irregular as $i)
			if ($i[0] == $verb) {
				if ($only_one)
					return explode("|", $i[2])[0];
				return $i[2];
			}
		if (array_key_exists($verb, self::$presentparticiple)) {
			$v = self::$presentparticiple[$verb];
			$matches = [];
			preg_match('/([a-zA-Z-]+([a-zA-Z]))\2ing$/', $v, $matches);
			if (count($matches) and $matches[1] == $verb)
				return $verb.$matches[2]."ed";
		}
		if ($verb[strlen($verb)-1] == "e")
			return $verb."d";
		return $verb."ed";
	}

	static public function thirdsingular($verb, $only_one=false) {
		if ($verb == "be") return "is";
		if ($verb == "have") return "has";
		$verb = preg_replace("/[^aeiou]y$/", "i", $verb);
		if (preg_match("/(i|o|ch|sh|ss|x)$/", $verb))
			return $verb."es";
		return $verb."s";
	}

	static public function presentparticiple($verb, $only_one=false) {
		if (array_key_exists($verb, self::$presentparticiple)) {
			if ($only_one)
				return explode("|", self::$presentparticiple[$verb])[0];
			return self::$presentparticiple[$verb];
		}
		if (endswith($verb,"ie")) return substr($verb,0,-2)."ying";
		if (endswith($verb,"e")) return substr($verb,0,-1)."ing";
		return $verb."ing";
	}
}
?>
